title: "My Journal"
baseurl: "/journal"  # Since the site is hosted under /journal
url: "https://miprogstuff.github.io"  # Replace with your GitHub Pages URL

# Optional settings
theme: "minima"  # You can choose a theme for the journal
